%PSOGSA source code v2.0, Generated by SeyedAli Mirjalili, 2011. 
%Adopted from: S. Mirjalili, S.Z. Mohd Hashim, “A New Hybrid PSOGSA 
%Algorithm for Function Optimization, in IEEE International Conference 
%on Computer and Information Application?ICCIA 2010), China, 2010, pp.374-377.
global errtol

clear all
clc

N = 10;                        % Size of the swarm " no of objects "
Max_Iteration  = 100;              % Maximum number of "iterations"
best_overall =NaN(30,9);
best_score_overall =NaN(30,1);
GlobalBestCost_overall =NaN(30,100);

Benchmark_Function_ID = 88; %Benchmark function ID
for iter=1:1
    tic;
    [gBestScore,gBest,GlobalBestCost,gProfit,gCost]= PSOGSA(Benchmark_Function_ID, N, Max_Iteration);
    toc
    best_overall(iter,:) = gBest;
    best_score_overall(iter) = gBestScore;
    GlobalBestCost_overall(iter,:) = GlobalBestCost;
    csvwrite('best_overall.csv',best_overall)
    csvwrite('best_score_overall.csv',best_score_overall)
    csvwrite('GlobalBestCost_overall.csv',GlobalBestCost_overall)
end

mean(best_overall)
mean(best_score_overall)
plot(GlobalBestCost,'-r');
title(['\fontsize{12}\bf Benchmark Function: F',num2str(Benchmark_Function_ID)]);
xlabel('\fontsize{12}\bf Iteration');ylabel('\fontsize{12}\bf Fitness(Best-so-far)');

% plot(GlobalBestCost,'-r');
% title(['\fontsize{12}\bf Benchmark Function: F',num2str(Benchmark_Function_ID)]);
% xlabel('\fontsize{12}\bf Iteration');ylabel('\fontsize{12}\bf Fitness(Best-so-far)');
